name: loadinglistview
description:  Flutter ListView and GridView that shows Loading Widgets before the real data is loaded.
version: 0.0.1
authors:
  - Morgan <michaeladesola1410@gmail.com>
homepage: https://github.com/De-Morgan/Loading-ListView

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
